// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbyynqvonuzvnodptjro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhieXlucXZvbnV6dm5vZHB0anJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MzUxNjUsImV4cCI6MjA3NjIxMTE2NX0.bqD9lS66iBEmO9MuCB4PtKxwk-uLu-necFEQMs1sJqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});